server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login
          uri: lb://login
          predicates:
            - Path=/login/**
        - id: email
          uri: lb://email
          predicates:
            - Path=/email/**
        - id: contact
          uri: lb://contact
          predicates:
            - Path=/contact/**
        - id: plans
          uri: lb://plans
          predicates:
            - Path=/plans/**